// import './globals.css'
// import { Inter } from 'next/font/google'
// import Providers from './provider'
// import Sidenav from './(components)/Sidebar/Sidenav'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" suppressHydrationWarning >
//       <body className={inter.className}>
//       <Providers>
//         <Sidenav/>
//         {children}
//         <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.js"></script>
//         </Providers>
//         </body>
//     </html>
//   )
// }
import './globals.css'
import { Inter } from 'next/font/google'
import Providers from './provider'
import Sidenav from './(components)/Sidebar/Sidenav'
// import ThemeButton from './(component)/themeButton/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body className={inter.className} >
        <Providers>
          <Sidenav/>
          {/* <ThemeButton/> */}
        {children}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.js"></script>
        </Providers>



        </body>
        
    </html>
  )
}
